### ISSUE TITLE
Issues Installing DTBO on Jetson Nano 2GB

### ISSUE THREAD

**Issue by Tengu246** [Seeed-Studio/seeed-linux-dtoverlays#19]
I just received the Can Bus V2 Hat that uses MCP2518FD chips. I followed the instruction on your wiki site for installing on Jetson Nano. The area that isnt working is when you say to run the sudo /opt/nvidia/jetson-io/config-by-hardware.py -n "Seeed 2xMCP2518FD"

This command returns the error:

Traceback (most recent call last):
  File "/opt/nvidia/jetson-io/config-by-hardware.py", line 64, in <module>
    main()
  File "/opt/nvidia/jetson-io/config-by-hardware.py", line 60, in main
    configure_jetson(jetson, hwlist, args.name)
  File "/opt/nvidia/jetson-io/config-by-hardware.py", line 36, in configure_jetson
    raise NameError("No configuration found for %s!" % hw)
NameError: No configuration found for Seeed 2xMCP2518FD!

With that failing the system does not detect the Hat even after reboot.

Please advise on how to fix this.

**Comment by Tengu246** [comment]
I realized by looking at the compatible carrier boards the Nano 2GB is not supported. Only the A0x and B0x boards are supported. I ordered a B01 so that should resolve the issue.
